// Local read-only Figma export MCP. Credentials stay in the provider's environment.
const fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),readline=require('node:readline');
function stateFile(home=os.homedir()){return process.env.PHIBY_STATE_FILE||path.join(process.platform==='darwin'?path.join(home,'Library','Application Support'):process.platform==='win32'?(process.env.APPDATA||path.join(home,'AppData','Roaming')):(process.env.XDG_CONFIG_HOME||path.join(home,'.config')),'Align','local','active.json');}
async function exportSelection(args,{fetchImpl=fetch,home=os.homedir()}={}){
  const run=JSON.parse(await fs.readFile(stateFile(home),'utf8'));
  const selection=new URL(run.project.pages[run.pageIndex].url),fileKey=selection.pathname.split('/')[2],nodeId=selection.searchParams.get('node-id').replaceAll('-',':');
  if(args.fileKey!==fileKey||args.nodeId.replaceAll('-',':')!==nodeId)throw Error('Only the current Align page may be exported.');
  const token=process.env.FIGMA_OAUTH_TOKEN||process.env.FIGMA_API_KEY;if(!token)throw Error('Figma credentials are missing from this MCP configuration.');
  const headers=process.env.FIGMA_OAUTH_TOKEN?{Authorization:`Bearer ${token}`}:{'X-Figma-Token':token};
  const response=await fetchImpl(`https://api.figma.com/v1/images/${encodeURIComponent(fileKey)}?ids=${encodeURIComponent(nodeId)}&format=png&scale=1`,{headers,signal:AbortSignal.timeout(45000)});
  if(!response.ok)throw Error(`Figma export returned HTTP ${response.status}.`);
  const data=await response.json(),url=data.images?.[nodeId];if(!url)throw Error('Figma did not return a render for this selection.');
  const imageUrl=new URL(url);if(imageUrl.protocol!=='https:'||!['figma.com','amazonaws.com'].some(d=>imageUrl.hostname===d||imageUrl.hostname.endsWith('.'+d)))throw Error('Unexpected Figma image host.');
  const image=await fetchImpl(url,{redirect:'error',signal:AbortSignal.timeout(45000)});if(!image.ok)throw Error(`Figma image returned HTTP ${image.status}.`);
  const chunks=[];let size=0;for await(const chunk of image.body){size+=chunk.length;if(size>40*1024*1024)throw Error('Reference image exceeds 40 MB.');chunks.push(chunk);}const bytes=Buffer.concat(chunks);if(!bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))throw Error('Figma returned an invalid PNG.');
  const root=await fs.realpath(run.project.directory);const expected=path.join(root,'.align','runs',run.id);if(path.resolve(run.directory)!==expected)throw Error('Unexpected run directory.');
  const dir=path.join(expected,`page-${run.pageIndex+1}`);await fs.mkdir(dir,{recursive:true});const real=await fs.realpath(dir);if(!real.startsWith(root+path.sep))throw Error('Export directory escapes project.');
  const output=path.join(real,'reference.png'),temp=path.join(real,`reference-${require('node:crypto').randomUUID()}.tmp`);await fs.writeFile(temp,bytes,{flag:'wx'});await fs.rename(temp,output);
  return {content:[{type:'text',text:JSON.stringify({reference:output,fileKey,nodeId,bytes:bytes.length})}]};
}
async function active(){return JSON.parse(await fs.readFile(stateFile(),'utf8'));}
async function atomic(file,value){const tmp=file+'.'+require('node:crypto').randomUUID()+'.tmp';await fs.writeFile(tmp,value,{flag:'wx'});await fs.rename(tmp,file);}
async function prepareBundle(args){
 const r=await active(),startedTicket=r.ticket;const shot=await exportSelection(args);const reference=JSON.parse(shot.content[0].text).reference,dir=path.dirname(reference);
 const token=process.env.FIGMA_OAUTH_TOKEN||process.env.FIGMA_API_KEY,headers=process.env.FIGMA_OAUTH_TOKEN?{Authorization:`Bearer ${token}`}:{'X-Figma-Token':token};
 const api=async suffix=>{const res=await fetch('https://api.figma.com/v1/'+suffix,{headers,signal:AbortSignal.timeout(45000)});if(!res.ok)throw Error(`Figma API returned HTTP ${res.status}.`);return res.json();};
 const nodeId=args.nodeId.replaceAll('-',':'),raw=await api(`files/${encodeURIComponent(args.fileKey)}/nodes?ids=${encodeURIComponent(nodeId)}`),node=raw.nodes?.[nodeId];if(!node?.document)throw Error('Selection node was not returned.');
 const refs=new Set();function scan(v){if(!v||typeof v!=='object')return;if(v.type==='IMAGE'&&v.imageRef&&v.visible!==false)refs.add(v.imageRef);for(const [k,x] of Object.entries(v))if(k!=='imageRef')scan(x);}scan(node.document);
 const fills=refs.size?(await api(`files/${encodeURIComponent(args.fileKey)}/images`)).meta?.images||{}:{};
 const assetDir=path.join(dir,'assets');await fs.mkdir(assetDir,{recursive:true});if(await fs.realpath(assetDir)!==assetDir)throw Error('Assets folder must not be a symbolic link.');const assets=[];
 const items=[...refs];for(let start=0;start<items.length;start+=4)await Promise.all(items.slice(start,start+4).map(async ref=>{const url=fills[ref];if(!url)throw Error('Figma omitted an image fill used by the selection.');const u=new URL(url);if(u.protocol!=='https:'||!['figma.com','amazonaws.com'].some(d=>u.hostname===d||u.hostname.endsWith('.'+d)))throw Error('Unexpected asset host.');const res=await fetch(url,{redirect:'error',signal:AbortSignal.timeout(45000)});if(!res.ok)throw Error(`Asset download returned HTTP ${res.status}.`);const chunks=[];let bytes=0;for await(const c of res.body){bytes+=c.length;if(bytes>40*1024*1024)throw Error('Asset exceeds 40 MB.');chunks.push(c);}const mime=(res.headers.get('content-type')||'').split(';')[0],ext={'image/png':'png','image/jpeg':'jpg','image/webp':'webp','image/svg+xml':'svg','image/gif':'gif'}[mime]||'bin';const file=path.join(assetDir,require('node:crypto').createHash('sha256').update(ref).digest('hex').slice(0,20)+'.'+ext);await atomic(file,Buffer.concat(chunks));assets.push({imageRef:ref,path:file,mime,bytes});}));
 if((await active()).ticket!==startedTicket)throw Error('Run changed during download. Resume with the current page.');
 await atomic(path.join(dir,'context.json'),JSON.stringify(node));
 await atomic(path.join(dir,'context.md'),`# ${r.project.pages[r.pageIndex].name}\nFigma: ${r.project.pages[r.pageIndex].url}\nUser brief: ${r.project.prompt}\nViewport: ${r.project.viewport.width} x ${r.project.viewport.height}\nReference: ${reference}\nExact node geometry, typography, fills, transforms and interactions: ${path.join(dir,'context.json')}\nOriginal image assets: ${JSON.stringify(assets,null,2)}\n`);
 const manifest={fileKey:args.fileKey,nodeId,reference,context:path.join(dir,'context.md'),geometry:path.join(dir,'context.json'),contextReader:'read_design_context: offset 0, follow nextOffset until null',assets};await atomic(path.join(dir,'bundle.json'),JSON.stringify(manifest,null,2));return {content:[{type:'text',text:JSON.stringify(manifest)}]};
}
function contextChunk(raw,offset=0){
 if(!Number.isSafeInteger(offset)||offset<0||offset>raw.length)throw Error('Invalid context offset.');
 const end=Math.min(offset+10000,raw.length);
 return {content:[{type:'text',text:JSON.stringify({offset,nextOffset:end<raw.length?end:null,totalCharacters:raw.length})+'\n'+raw.slice(offset,end)}]};
}
async function readContext(args){
 const r=await active(),root=await fs.realpath(r.project.directory),dir=await fs.realpath(r.directory);
 if(dir!==path.join(root,'.align','runs',r.id))throw Error('Unexpected run directory.');
 const file=await fs.realpath(path.join(dir,`page-${r.pageIndex+1}`,'context.json'));
 if(!file.startsWith(dir+path.sep))throw Error('Context path escapes the run.');
 return contextChunk(await fs.readFile(file,'utf8'),args.offset||0);
}
const contextTool={name:'read_design_context',description:'Read the complete current Figma JSON without line truncation. All original fields and values are retained. Start at offset 0; repeat with nextOffset until it is null. Chunks concatenate to the exact JSON.',inputSchema:{type:'object',properties:{offset:{type:'integer',minimum:0}},additionalProperties:false}};
async function submitPrompt(args){const r=await active();if(!['manager','completed'].includes(r.status))throw Error('Stale handoff: manager is not active.');if(typeof args.prompt!=='string'||args.prompt.length<30||args.prompt.length>40000)throw Error('Provide the structured builder prompt (30–40000 characters).');const root=await fs.realpath(r.project.directory),dir=await fs.realpath(r.directory);if(dir!==path.join(root,'.align','runs',r.id))throw Error('Unexpected run directory.');const page=path.join(dir,`page-${r.pageIndex+1}`);let reference=path.join(page,'reference.png');try{const manifest=JSON.parse(await fs.readFile(path.join(page,'bundle.json'),'utf8'));if(manifest.reference)reference=manifest.reference;}catch{}await atomic(path.join(dir,'manager-action.json'),JSON.stringify({ticket:args.ticket||r.ticket,type:'build',prompt:args.prompt,reference}));return {content:[{type:'text',text:'Builder task submitted. End your turn now; Align starts the builder.'}]};}
const tool={name:'get_screenshot',description:'Export the current Align Figma selection to its shared page folder as reference.png. Returns its absolute local path. Uses the existing provider Figma credentials.',inputSchema:{type:'object',properties:{fileKey:{type:'string',pattern:'^[a-zA-Z0-9]+$'},nodeId:{type:'string',pattern:'^[0-9]+[:\\-][0-9]+$'}},required:['fileKey','nodeId'],additionalProperties:false}};
const bundleTool={...tool,name:'prepare_design_bundle',description:'ONE call downloads the current selection reference PNG and every image fill, and saves exact Figma geometry, typography, transforms and context in the selected project page folder. Returns local paths. Use this first, then submit_builder_prompt. No shell or extra download scripts needed.'};
const handoffTool={name:'submit_builder_prompt',description:'Submit the complete context-aware builder prompt to Align after prepare_design_bundle. No file-edit or shell tool needed. End your turn afterward.',inputSchema:{type:'object',properties:{ticket:{type:'string'},prompt:{type:'string'}},required:['ticket','prompt'],additionalProperties:false}};
async function dispatch(m){if(m.method==='initialize')return {protocolVersion:m.params?.protocolVersion||'2024-11-05',capabilities:{tools:{}},serverInfo:{name:'align-figma-export',version:'1.0.0'}};if(m.method==='ping')return {};if(m.method==='tools/list')return {tools:[tool,bundleTool,handoffTool,contextTool]};if(m.method==='tools/call'){if(m.params?.name===contextTool.name){try{return await readContext(m.params.arguments||{});}catch(e){return {isError:true,content:[{type:'text',text:e.message}]};}}if(m.params?.name===handoffTool.name){try{return await submitPrompt(m.params.arguments);}catch(e){return {isError:true,content:[{type:'text',text:e.message}]};}}if(![tool.name,bundleTool.name].includes(m.params?.name))throw Error('Unknown tool.');const a=m.params.arguments;if(!a||typeof a.fileKey!=='string'||typeof a.nodeId!=='string')throw Error('fileKey and nodeId are required.');try{return await (m.params.name===bundleTool.name?prepareBundle(a):exportSelection(a));}catch(e){return {isError:true,content:[{type:'text',text:e.message}]};}}throw Error('Unsupported method.');}
if(require.main===module){let chain=Promise.resolve();readline.createInterface({input:process.stdin}).on('line',line=>{chain=chain.then(async()=>{let m;try{m=JSON.parse(line);if(m.id===undefined)return;const result=await dispatch(m);process.stdout.write(JSON.stringify({jsonrpc:'2.0',id:m.id,result})+'\n');}catch(e){process.stdout.write(JSON.stringify({jsonrpc:'2.0',id:m?.id??null,error:{code:-32603,message:e.message}})+'\n');}});});}
module.exports={exportSelection,contextChunk};
